package nieto.genm.login_android.data.local

import androidx.room.RoomDatabaseConstructor

actual object AppDBConstructor : RoomDatabaseConstructor<AppDB> {
    actual override fun initialize(): AppDB = error("Generated by Room")
}